(()=>{'use strict';
const SUITS=[{key:'S',g:'♠',color:'black'},{key:'H',g:'♥',color:'red'},{key:'D',g:'♦',color:'red'},{key:'C',g:'♣',color:'black'}],R=['','A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const TOTAL=104,COLS=10,SEQS=8,SAVE='sani-spider-ultimate-v7',HINT_REPEAT_LIMIT=3;let state=null,history=[],drag=null,timer=null,startedAt=0,elapsedBase=0,paused=false,busy=false,hintTimer=null,suppressClickUntil=0,moveTrail=[],stateSeen=new Map();
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
function suitOf(k){return SUITS.find(s=>s.key===k)}
function buildDeck(numSuits){const copies=8/numSuits,deck=[];let id=0;for(const s of SUITS.slice(0,numSuits))for(let copy=0;copy<copies;copy++)for(let rank=1;rank<=13;rank++)deck.push({id:'c'+id++,suit:s.key,glyph:s.g,color:s.color,rank,faceUp:false});if(deck.length!==TOTAL||copies%1!==0)throw new Error('Deck must contain exactly 104 cards');for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}return deck}
function newGame(numSuits){stopTimer();clearHint();cancelDrag();busy=false;moveTrail=[];stateSeen=new Map();const deck=buildDeck(numSuits),columns=Array.from({length:COLS},()=>[]);for(let c=0;c<COLS;c++){const count=c<4?6:5;for(let i=0;i<count;i++){const card=deck.pop();card.faceUp=i===count-1;columns[c].push(card)}}const stock=[];while(deck.length)stock.push(deck.splice(deck.length-10,10));state={version:7,numSuits,columns,stock,completed:0,moves:0,score:500,finished:false};if(!validateState())throw new Error('Invalid initial state');history=[];elapsedBase=0;startedAt=Date.now();paused=false;showGame();save();render();startTimer();setUndo()}
function validateState(){if(!state||!Array.isArray(state.columns)||state.columns.length!==COLS)return false;const cards=state.columns.flat().concat(state.stock.flat());if(cards.length!==TOTAL)return false;const ids=new Set(cards.map(c=>c.id));return ids.size===TOTAL&&cards.every(c=>c&&Number.isInteger(c.rank)&&c.rank>=1&&c.rank<=13&&SUITS.some(s=>s.key===c.suit))}function snapshot(){return {columns:clone(state.columns),stock:clone(state.stock),completed:state.completed,moves:state.moves,score:state.score}}
function stateKey(){return state.columns.map(c=>c.map(x=>x.id+':'+(x.faceUp?1:0)).join(',')).join('|')+'#'+state.stock.map(b=>b.map(x=>x.id).join(',')).join('|')+'#'+state.completed}
function recordState(){const k=stateKey(),n=(stateSeen.get(k)||0)+1;stateSeen.set(k,n);return n}
function recordMove(from,index,to){moveTrail.push(from+':'+index+'>'+to);if(moveTrail.length>12)moveTrail.shift()}
function repetitionDetected(){if(!state.stock.length)return false;const recent=moveTrail.slice(-6);if(recent.length<3)return false;const counts=new Map();for(const k of recent)counts.set(k,(counts.get(k)||0)+1);return Math.max(...counts.values())>=HINT_REPEAT_LIMIT || Math.max(...stateSeen.values())>=HINT_REPEAT_LIMIT}
function pushHistory(){history.push(snapshot());setUndo()}
function isRun(col,index){if(!col[index]||!col[index].faceUp)return false;for(let k=index+1;k<col.length;k++){const a=col[k-1],b=col[k];if(!b.faceUp||b.suit!==a.suit||b.rank!==a.rank-1)return false}return true}
function canPlace(card,dst){return !dst.length||(dst.at(-1).faceUp&&dst.at(-1).rank===card.rank+1)}
function sequenceReady(col){if(col.length<13)return false;const seq=col.slice(-13),s=seq[0].suit;return seq[0].rank===13&&seq.every((c,i)=>c.faceUp&&c.suit===s&&c.rank===13-i)}
function completeSequence(c){const col=state.columns[c];if(!sequenceReady(col))return false;const suit=col.at(-1).suit;col.splice(-13);if(col.length)col.at(-1).faceUp=true;state.completed++;state.score+=100;animateFoundation(suit);return true}
function tryMove(from,index,to){if(busy||paused||state.finished||from===to)return false;const src=state.columns[from],dst=state.columns[to],card=src[index];if(!isRun(src,index)||!canPlace(card,dst))return false;pushHistory();const moved=src.splice(index);dst.push(...moved);if(src.length)src.at(-1).faceUp=true;state.moves++;state.score=Math.max(0,state.score-1);recordMove(from,index,to);recordState();save();render();completeSequence(to);save();render();checkEnd();return true}
function deal(){if(busy||paused||state.finished)return;if(!state.stock.length){toast('Резерв уже пуст.');return}if(state.columns.some(c=>c.length===0)){toast('Раздача заблокирована: сначала заполните пустой столбец.');flashColumns();return}busy=true;clearHint();pushHistory();const batch=state.stock.pop();batch.forEach(card=>{card.faceUp=true});for(let i=0;i<COLS;i++)state.columns[i].push(batch[i]);state.moves++;state.score=Math.max(0,state.score-1);moveTrail=[];stateSeen=new Map();recordState();save();render();animateDeal(batch.length,()=>{for(let i=0;i<COLS;i++)completeSequence(i);busy=false;save();render();checkEnd();setUndo()})}
function allMoves(){if(!state)return[];const moves=[];for(let from=0;from<COLS;from++){const src=state.columns[from];for(let index=src.length-1;index>=0;index--){if(!src[index].faceUp)break;if(!isRun(src,index))continue;for(let to=0;to<COLS;to++){if(to===from||!canPlace(src[index],state.columns[to]))continue;const dst=state.columns[to],same=dst.length&&dst.at(-1).suit===src[index].suit;let score=same?100:10;if(index>0&&!src[index-1].faceUp)score+=70;if(!dst.length)score+=40;score+=(src.length-index)*2;moves.push({from,index,to,score})}}}return moves.sort((a,b)=>b.score-a.score)}
function hint(){if(!state||paused||busy||state.finished)return;clearHint();if(repetitionDetected()){if(state.stock.length){highlightDealHint();toast('Похоже, ходы зациклились. Подсказка: сделайте новую раздачу.');return}toast('Ходы зациклились, но резерв пуст — доступных новых ходов нет.');return}const m=allMoves()[0];if(m){showHint(m);return}if(state.stock.length){highlightDealHint();toast('Ходов на поле нет — подсказка рекомендует новую раздачу.');return}toast('Доступных ходов нет. Резерв пуст — игра проиграна.');}

function highlightDealHint(){const stock=$('stock-visual'),btn=$('btn-deal');stock?.classList.add('hint-stock');btn?.classList.add('hint-deal');hintTimer=setTimeout(clearHint,4500)}
function showHint(m){const source=document.querySelector(`.card[data-col="${m.from}"][data-index="${m.index}"]`),target=document.querySelector(`.column[data-col="${m.to}"]`);if(!source||!target)return;source.classList.add('hint-card');target.classList.add('hint-target');const a=source.getBoundingClientRect(),b=target.getBoundingClientRect(),board=document.querySelector('.board').getBoundingClientRect(),sx=a.right-board.left-6,sy=a.top+a.height*.48-board.top,tx=b.left+Math.min(b.width*.55,b.width-8)-board.left,ty=b.top+b.height*.22-board.top;const layer=$('hint-layer');layer.innerHTML=`<svg class="hint-arrow" style="left:0;top:0;width:100%;height:100%" viewBox="0 0 ${board.width} ${board.height}" preserveAspectRatio="none"><path d="M ${sx} ${sy} C ${(sx+tx)/2} ${sy-35}, ${(sx+tx)/2} ${ty+35}, ${tx-22} ${ty}"/><polygon points="${tx-2},${ty} ${tx-30},${ty-15} ${tx-24},${ty+13}"/></svg><div class="hint-label" style="left:${Math.max(6,(sx+tx)/2-55)}px;top:${Math.max(6,Math.min(board.height-42,(sy+ty)/2-22))}px">ПЕРЕМЕСТИТЬ</div>`;hintTimer=setTimeout(clearHint,4500)}
function clearHint(){if(hintTimer)clearTimeout(hintTimer);hintTimer=null;document.querySelectorAll('.hint-card,.hint-target,.drop-ok,.drop-bad,.hint-stock,.hint-deal').forEach(x=>x.classList.remove('hint-card','hint-target','drop-ok','drop-bad','hint-stock','hint-deal'));const layer=$('hint-layer');if(layer)layer.innerHTML=''}
function undo(){if(!state||!history.length||paused||busy||state.finished)return;const prev=history.pop();state=Object.assign(state,prev);state.score=Math.max(0,prev.score-1);moveTrail=[];stateSeen=new Map([[stateKey(),1]]);save();render();setUndo();toast('Ход отменён · −1 очко')}
function checkEnd(){if(state.completed>=SEQS){finish(true);return}if(!state.stock.length&&!allMoves().length)finish(false)}
function finish(win){state.finished=true;stopTimer();save();$('end-icon').textContent=win?'🏆':'🕸';$('end-title').textContent=win?'Победа!':'Игра окончена';$('end-sub').textContent=win?'Все 8 последовательностей собраны.':'Нет доступных ходов и резерв пуст.';$('end-score').textContent=state.score;$('end-moves').textContent=state.moves;$('end-time').textContent=fmt(elapsed());$('end-modal').classList.remove('hidden');setUndo()}
function elapsed(){return elapsedBase+(!paused&&startedAt?Math.floor((Date.now()-startedAt)/1000):0)}function fmt(sec){return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function startTimer(){if(timer)clearInterval(timer);timer=setInterval(()=>{$('stat-time').textContent=fmt(elapsed())},1000)}function stopTimer(){if(timer)clearInterval(timer);timer=null;if(startedAt){elapsedBase=elapsed();startedAt=0}}
function pause(){if(!state||state.finished||paused)return;cancelDrag();elapsedBase=elapsed();startedAt=0;paused=true;save();$('pause-modal').classList.remove('hidden');render()}
function resume(){if(!state||!paused)return;paused=false;startedAt=Date.now();$('pause-modal').classList.add('hidden');startTimer();save();render()}
function save(){if(!state)return;try{localStorage.setItem(SAVE,JSON.stringify({version:7,state,history,elapsed:elapsed()}))}catch(e){}}
function load(){try{const x=JSON.parse(localStorage.getItem(SAVE)||'null');if(!x?.state||x.state.finished||!Array.isArray(x.state.columns)||x.state.columns.length!==10)return false;state=x.state;if(!validateState())return false;history=Array.isArray(x.history)?x.history:[];moveTrail=[];stateSeen=new Map([[stateKey(),1]]);elapsedBase=Number(x.elapsed)||0;startedAt=0;paused=true;showGame();render();$('pause-modal').classList.remove('hidden');$('btn-continue').classList.remove('hidden');return true}catch(e){return false}}
function showGame(){$('start-screen').classList.add('hidden');$('game').classList.remove('hidden');$('end-modal').classList.add('hidden')}
function menu(){cancelDrag();if(state&&!state.finished)save();stopTimer();$('game').classList.add('hidden');$('start-screen').classList.remove('hidden');$('pause-modal').classList.add('hidden');$('end-modal').classList.add('hidden');$('btn-continue').classList.toggle('hidden',!state||state.finished)}
function setUndo(){$('btn-undo').disabled=!state||!history.length||paused||busy||state.finished}
function render(){if(!state)return;$('stat-score').textContent=state.score;$('stat-time').textContent=fmt(elapsed());$('stat-moves').textContent=state.moves;$('stat-sequences').textContent=`${state.completed}/8`;$('stat-stock').textContent=state.stock.length;$('stat-difficulty').textContent=state.numSuits+' маст.';$('btn-deal').disabled=paused||busy||state.finished||!state.stock.length||state.columns.some(c=>c.length===0);renderFoundations();renderStock();const root=$('tableau');root.innerHTML='';const cardH=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--card-h'))||160;state.columns.forEach((col,c)=>{const el=document.createElement('div');el.className='column';el.dataset.col=c;const available=Math.max(70,window.innerHeight-190);const off=Math.max(18,Math.min(42,Math.floor(available/Math.max(col.length,9))));el.style.height=Math.max(cardH,(col.length-1)*off+cardH)+'px';col.forEach((card,i)=>{const ce=cardEl(card,c,i);ce.style.top=i*off+'px';ce.style.zIndex=i;el.appendChild(ce)});root.appendChild(el)});setUndo()}
function renderFoundations(){const f=$('foundations');f.innerHTML='';for(let i=0;i<SEQS;i++){const el=document.createElement('div');el.className='foundation'+(i<state.completed?' done':'');el.innerHTML=i<state.completed?`<div class="mini-card"><b>K</b><span>${SUITS[i%state.numSuits].g}</span></div>`:'♠';f.appendChild(el)}}
function renderStock(){const s=$('stock-visual');s.innerHTML='';for(let i=0;i<Math.min(5,Math.max(1,state.stock.length));i++){const d=document.createElement('i');d.style.transform=`translate(${i*2}px,${i*2}px)`;s.appendChild(d)}}
function pipMarkup(rank,glyph){const map={2:[4,6],3:[3,5,7],4:[3,4,6,7],5:[3,4,5,6,7],6:[3,4,5,6,7,8],7:[3,4,5,6,7,8,9],8:[3,4,5,6,7,8,9,10],9:[3,4,5,6,7,8,9,10,11],10:[3,4,5,6,7,8,9,10,11,12]};if(rank===1)return `<div class="ace-art">${glyph}</div>`;const arr=map[rank]||[];return `<div class="pips">${arr.map((_,i)=>`<span class="pip-${i}">${glyph}</span>`).join('')}</div>`}
function cardEl(card,c,i){const el=document.createElement('div');el.className='card';el.dataset.col=c;el.dataset.index=i;el.dataset.id=card.id;if(card.faceUp){const red=card.color==='red';let center;if(card.rank===1)center=pipMarkup(1,card.glyph);else if(card.rank>=11)center=`<div class="court-art"><div class="court-inner"><div class="court-letter">${R[card.rank]}</div><div class="court-suit">${card.glyph}</div></div></div>`;else center=pipMarkup(card.rank,card.glyph);el.innerHTML=`<div class="card-face ${red?'is-red':'is-black'}"><div class="corner">${R[card.rank]}<br>${card.glyph}</div>${center}<div class="corner bottom">${R[card.rank]}<br>${card.glyph}</div></div>`;el.addEventListener('pointerdown',e=>startDrag(e,c,i));el.addEventListener('click',()=>tap(c,i))}else el.innerHTML='<div class="card-back"></div>';return el}
function tap(c,i){if(paused||busy||Date.now()<suppressClickUntil)return;if(state.selection){if(state.selection.col===c&&state.selection.index===i){state.selection=null;render();return}if(tryMove(state.selection.col,state.selection.index,c)){state.selection=null;return}}if(isRun(state.columns[c],i)){state.selection={col:c,index:i};render()}}
function startDrag(e,c,i){if(paused||busy||state.finished||drag||!isRun(state.columns[c],i))return;e.preventDefault();clearHint();const cardElm=document.querySelector(`.card[data-col="${c}"][data-index="${i}"]`);if(!cardElm)return;const rect=cardElm.getBoundingClientRect(),cards=state.columns[c].slice(i),offset=Math.min(34,rect.height*.25),ghost=document.createElement('div');ghost.className='drag-ghost';ghost.style.width=rect.width+'px';ghost.style.height=rect.height+(cards.length-1)*offset+'px';cards.forEach((card,k)=>{const g=document.createElement('div');g.className='ghost-card';g.style.top=k*offset+'px';g.innerHTML=card.faceUp?cardEl(card,c,i+k).innerHTML:'<div class="card-back"></div>';ghost.appendChild(g)});$('drag-layer').appendChild(ghost);drag={from:c,index:i,pointer:e.pointerId,ghost,source:cardElm,origin:{x:rect.left,y:rect.top}};cardElm.classList.add('dragging-source');moveGhost(e);window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',onPointerUp);window.addEventListener('pointercancel',onPointerCancel)}
function moveGhost(e){if(!drag)return;drag.ghost.style.left=(e.clientX-drag.ghost.offsetWidth*.15)+'px';drag.ghost.style.top=(e.clientY-18)+'px'}
function moveDrag(e){if(!drag||e.pointerId!==drag.pointer)return;moveGhost(e);highlightDrop(e.clientX,e.clientY)}
function highlightDrop(x,y){document.querySelectorAll('.column').forEach(c=>c.classList.remove('drop-ok','drop-bad'));const el=document.elementFromPoint(x,y)?.closest('.column');if(!el||!drag)return;const to=+el.dataset.col,ok=to!==drag.from&&canPlace(state.columns[drag.from][drag.index],state.columns[to]);el.classList.add(ok?'drop-ok':'drop-bad')}
function onPointerUp(e){if(!drag||e.pointerId!==drag.pointer)return;const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.column');finishDrag(el?+el.dataset.col:-1)}
function onPointerCancel(e){if(!drag||e.pointerId!==drag.pointer)return;suppressClickUntil=Date.now()+260;returnGhost(true)}
function finishDrag(to){if(!drag)return;const d=drag;suppressClickUntil=Date.now()+260;cleanupDragListeners();if(to>=0&&to!==d.from&&canPlace(state.columns[d.from][d.index],state.columns[to])){d.source?.classList.remove('dragging-source');d.ghost?.remove();drag=null;tryMove(d.from,d.index,to);return}returnGhost(false)}
function returnGhost(cancelled){if(!drag)return;const d=drag;d.ghost.style.transition='left .18s ease, top .18s ease, opacity .18s ease';d.ghost.style.left=d.origin.x+'px';d.ghost.style.top=d.origin.y+'px';d.ghost.style.opacity='0';setTimeout(()=>{d.source?.classList.remove('dragging-source');d.ghost?.remove();if(drag===d)drag=null},190)}
function cleanupDragListeners(){window.removeEventListener('pointermove',moveDrag);window.removeEventListener('pointerup',onPointerUp);window.removeEventListener('pointercancel',onPointerCancel)}
function cancelDrag(){if(!drag)return;const d=drag;cleanupDragListeners();d.source?.classList.remove('dragging-source');d.ghost?.remove();drag=null;document.querySelectorAll('.column').forEach(c=>c.classList.remove('drop-ok','drop-bad'))}
function animateDeal(count,done){const cards=document.querySelectorAll('.card');const start=Math.max(0,cards.length-count);for(let i=start;i<cards.length;i++)cards[i].animate([{transform:'translateY(-38px) rotate(-1deg)',opacity:.35},{transform:'translateY(0) rotate(0)',opacity:1}],{duration:240,delay:(i-start)*38,easing:'cubic-bezier(.2,.8,.2,1)'});setTimeout(done,Math.min(900,240+count*38))}
function animateFoundation(suit){const f=document.querySelector('.foundation-row');f?.animate([{transform:'scale(.985)',filter:'brightness(1)'},{transform:'scale(1.01)',filter:'brightness(1.8)'},{transform:'scale(1)',filter:'brightness(1)'}],{duration:420,easing:'ease-out'})}
function flashColumns(){document.querySelectorAll('.column').forEach(x=>{x.classList.add('drop-bad');setTimeout(()=>x.classList.remove('drop-bad'),600)})}
function toast(text){const el=$('toast');el.textContent=text;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2800)}
function info(title,html){$('info-content').innerHTML=`<h3>${title}</h3>${html}`;$('info-modal').classList.remove('hidden')}
$('btn-rules').onclick=()=>info('Правила Spider Solitaire',`<p><b>Цель:</b> собрать 8 полных последовательностей K–A одной масти.</p><h4>Перемещение</h4><ul><li>Одну открытую карту можно положить на карту ровно на 1 ранг выше — масть цели не важна.</li><li>Стопка переносится целиком только если она открыта, строго убывает и вся одной масти.</li><li>Пустой столбец принимает любую одиночную карту или допустимую стопку.</li></ul><h4>Раздача</h4><p>Резерв всегда содержит 50 карт и выдаёт ровно по одной карте в каждый из 10 столбцов. При пустом столбце раздача запрещена.</p><h4>Счёт</h4><p>Старт — 500. Каждый ход −1, каждое Undo −1, каждая собранная последовательность +100. Счёт не ниже нуля.</p>`);
$('btn-about').onclick=()=>info('SANI GROUP',`<p><b>ПАУК</b> — карточная игра SANI GROUP.</p><p>Визуальный стиль этой версии построен на тёмном дереве, зелёном сукне, золотой фольге и фирменной рубашке SANI GROUP.</p><p>© 2026 SANI GROUP</p>`);
$('btn-continue').onclick=()=>{if(load())resume()};document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>newGame(+b.dataset.suits));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.overlay').classList.add('hidden'));$('btn-deal').onclick=deal;$('btn-hint').onclick=hint;$('btn-undo').onclick=undo;$('btn-pause').onclick=pause;$('btn-resume').onclick=resume;$('btn-game-menu').onclick=menu;$('btn-pause-menu').onclick=menu;$('btn-end-menu').onclick=menu;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state&&!state.finished&&!paused)pause()});window.addEventListener('blur',()=>{if(state&&!state.finished&&!paused)pause()});window.addEventListener('resize',()=>{if(state&&!paused&&!busy)render()});window.addEventListener('keydown',e=>{if(e.key==='Escape'&&drag){cancelDrag();toast('Перемещение отменено')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}});window.addEventListener('beforeunload',()=>state&&!state.finished&&save());
try{if(localStorage.getItem(SAVE))$('btn-continue').classList.remove('hidden')}catch(e){}$('start-screen').classList.remove('hidden');
})();
