(() => {
  'use strict';
  const SUITS=[{k:'S',g:'♠',c:'black'},{k:'H',g:'♥',c:'red'},{k:'D',g:'♦',c:'red'},{k:'C',g:'♣',c:'black'}];
  const R=['','A','2','3','4','5','6','7','8','9','10','J','Q','K'];
  const COLS=10,TOTAL=104,SEQS=8,KEY='sani_spider_v8',STATS_KEY='sani_spider_stats_v1';
  let state=null,history=[],drag=null,timerId=null,lastTick=0,paused=false,hintTimer=null,hintKey=null,hintRepeats=0,moveBusy=false;
  const $=id=>document.getElementById(id);
  const clone=o=>JSON.parse(JSON.stringify(o));
  function deckFor(n){const per=8/n,deck=[];let id=0;for(const s of SUITS.slice(0,n))for(let copy=0;copy<per;copy++)for(let rank=1;rank<=13;rank++)deck.push({id:'c'+id++,suit:s.k,glyph:s.g,color:s.c,rank,faceUp:false});for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}if(deck.length!==TOTAL)throw Error('Deck must be 104');return deck}
  function snapshot(){return {columns:clone(state.columns),stock:clone(state.stock),completed:state.completed,moves:state.moves,score:state.score,elapsed:elapsed()}}
  function restore(s){state.columns=clone(s.columns);state.stock=clone(s.stock);state.completed=s.completed;state.moves=s.moves;state.score=s.score;state.elapsedBase=s.elapsed;state.startedAt=paused?0:Date.now();render();}
  function newGame(n){clearHint();const d=deckFor(n),cols=Array.from({length:10},()=>[]);for(let c=0;c<10;c++){const count=c<4?6:5;for(let i=0;i<count;i++){const card=d.pop();card.faceUp=i===count-1;cols[c].push(card)}}const stock=[];while(d.length)stock.push(d.splice(0,10));state={numSuits:n,columns:cols,stock,completed:0,moves:0,score:500,elapsedBase:0,startedAt:Date.now(),finished:false};history=[];paused=false;recordStat('started');save();$('startScreen').classList.add('hidden');$('gameScreen').classList.remove('hidden');$('pauseModal').classList.add('hidden');$('endModal').classList.add('hidden');updateLabels();render();startTimer()}
  function elapsed(){if(!state)return 0;return state.elapsedBase+(state.startedAt?Math.floor((Date.now()-state.startedAt)/1000):0)}
  function fmt(t){const m=Math.floor(t/60).toString().padStart(2,'0'),s=(t%60).toString().padStart(2,'0');return m+':'+s}
  function startTimer(){stopTimer();if(paused||!state||state.finished)return;timerId=setInterval(()=>{$('timer').textContent=fmt(elapsed())},500)}
  function stopTimer(){if(timerId)clearInterval(timerId);timerId=null}
  function pauseGame(auto=false){if(!state||state.finished||paused)return;state.elapsedBase=elapsed();state.startedAt=0;paused=true;stopTimer();save();$('pauseModal').classList.remove('hidden');if(auto)toast('Игра поставлена на паузу — вкладка была скрыта.')}
  function resumeGame(){if(!state||state.finished)return;paused=false;state.startedAt=Date.now();$('pauseModal').classList.add('hidden');startTimer();save();render()}
  function isRun(col,i){if(i<0||i>=col.length||!col[i].faceUp)return false;for(let k=i+1;k<col.length;k++)if(!col[k].faceUp||col[k].suit!==col[k-1].suit||col[k].rank!==col[k-1].rank-1)return false;return true}
  function canPlace(card,target){return target.length===0||target[target.length-1].faceUp&&target[target.length-1].rank===card.rank+1}
  function pushHistory(){history.push(snapshot());save()}
  function move(from,i,to){if(moveBusy||!state||paused||state.finished||from===to)return false;const a=state.columns[from],b=state.columns[to];if(!isRun(a,i)||!canPlace(a[i],b))return false;pushHistory();b.push(...a.splice(i));if(a.length)a[a.length-1].faceUp=true;state.moves++;state.score=Math.max(0,state.score-1);checkSequence(to);resetCycle();render();save();checkEnd();return true}
  function checkSequence(c){const col=state.columns[c];if(col.length<13)return;const x=col.slice(-13);if(x[0].rank!==13||x.some((v,i)=>!v.faceUp||v.suit!==x[0].suit||v.rank!==13-i))return;col.splice(-13);if(col.length)col.at(-1).faceUp=true;state.completed++;state.score=Math.max(0,state.score+100);toast('K–A собраны! +100 очков');render()}
  function deal(){if(moveBusy||!state||paused||state.finished||!state.stock.length)return;if(state.columns.some(c=>c.length===0)){toast('Нельзя раздавать: сначала заполните пустой столбец.');return}moveBusy=true;pushHistory();const batch=state.stock.pop();batch.forEach((card,i)=>{card.faceUp=true;state.columns[i].push(card);checkSequence(i)});state.moves++;state.score=Math.max(0,state.score-1);resetCycle();render();save();moveBusy=false;checkEnd()}
  function undo(){if(moveBusy||paused||state.finished||!history.length||!state)return false;clearHint();const s=history.pop();restore(s);state.score=Math.max(0,state.score-1);save();toast('Ход отменён • −1 очко');return true;}
  function legalMoves(){const out=[];for(let c=0;c<10;c++){const col=state.columns[c];for(let i=col.length-1;i>=0;i--){if(!col[i].faceUp)break;if(!isRun(col,i))continue;for(let t=0;t<10;t++){if(t===c)continue;if(canPlace(col[i],state.columns[t])){let score=0;const target=state.columns[t];if(target.length&&target.at(-1).suit===col[i].suit)score+=100;else if(target.length)score+=20;if(i>0&&!col[i-1].faceUp)score+=80;if(target.length===0)score+=5;out.push({from:c,index:i,to:t,score})}}}}return out.sort((a,b)=>b.score-a.score)}
  function positionKey(){return state.columns.map(c=>c.map(x=>x.id+':'+(x.faceUp?1:0)).join(',')).join('|')+'#'+state.stock.length}
  function resetCycle(){hintKey=null;hintRepeats=0}
  function hint(){clearHint();if(!state||paused)return;const moves=legalMoves();if(!moves.length){if(state.stock.length){toast('Ходов нет — подсказка: сделайте новую раздачу.');flashDeal();}else toast('Ходов больше нет и резерв пуст.');return}const m=moves[0];const key=positionKey()+'|'+m.from+'>'+m.index+'>'+m.to;if(key===hintKey)hintRepeats++;else{hintKey=key;hintRepeats=1}if(hintRepeats>=3){toast(state.stock.length?'Ход повторяется уже 3 раза. Сделайте новую раздачу.':'Ход зациклился 3 раза. Резерв уже пуст.');if(state.stock.length)flashDeal();return}showHintMove(m)}
    function showHintMove(m){
    const src=document.querySelector(`.card[data-col="${m.from}"][data-index="${m.index}"]`),target=document.querySelectorAll('.column')[m.to];
    if(!src||!target)return;
    src.classList.add('hint-source');target.classList.add('hint-target');
    const a=src.getBoundingClientRect(),b=target.getBoundingClientRect();
    const x1=a.right-4,y1=a.top+a.height/2,x2=b.left+8,y2=b.top+Math.min(70,b.height/2);
    const dx=x2-x1,dy=y2-y1,arr=$('hintArrow');
    arr.style.left=x1+'px';arr.style.top=(y1-38)+'px';
    arr.style.width=Math.max(90,Math.hypot(dx,dy))+'px';
    arr.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;
    arr.classList.remove('hidden');
    hintTimer=setTimeout(()=>clearHint(),4200);
  }
  function flashDeal(){const b=$('dealBtn');b.classList.add('hint-deal');setTimeout(()=>b.classList.remove('hint-deal'),3000)}
    function clearHint(){document.querySelectorAll('.hint-source,.hint-target').forEach(e=>e.classList.remove('hint-source','hint-target'));$('hintArrow').classList.add('hidden');if(hintTimer){clearTimeout(hintTimer);hintTimer=null}}
  function render(){if(!state)return;$('difficulty').textContent=state.numSuits===1?'1 масть':state.numSuits===2?'2 масти':'4 масти';$('completed').textContent=state.completed+'/8';$('moves').textContent=state.moves;$('score').textContent=state.score;$('timer').textContent=fmt(elapsed());$('stockCount').textContent=state.stock.length;$('dealBtn').disabled=!state.stock.length||state.finished||paused;$('undoBtn').disabled=!history.length||paused;renderFoundations();renderTableau()}
  function updateLabels(){render()}
  function renderFoundations(){const f=$('foundations');f.innerHTML='';for(let i=0;i<8;i++){const e=document.createElement('div');e.className='foundation'+(i<state.completed?' filled':'');e.textContent=i<state.completed?'♠':'♠';f.appendChild(e)}}
  function cardEl(card,c,i){const e=document.createElement('div');e.className='card '+(card.color==='red'?'is-red':'is-black');e.dataset.col=c;e.dataset.index=i;e.dataset.id=card.id;e.style.top=`${i} * var(--offset)`;if(card.faceUp){let art='';if(card.rank>=11)art=`<div class="face-art">${R[card.rank]}</div>`;e.innerHTML=`<div class="card-face"><div class="corner top"><span>${R[card.rank]}</span><span>${card.glyph}</span></div><div class="pip">${card.rank>=11?'':card.glyph}</div>${art}<div class="corner bottom"><span>${R[card.rank]}</span><span>${card.glyph}</span></div></div>`;e.addEventListener('pointerdown',ev=>beginDrag(ev,c,i))}else e.innerHTML='<div class="card-back"></div>';return e}
  function renderTableau(){const t=$('tableau');t.innerHTML='';state.columns.forEach((col,c)=>{const el=document.createElement('div');el.className='column';el.dataset.col=c;el.style.height=`calc(var(--cardH) + ${Math.max(0,col.length-1)} * var(--offset))`;col.forEach((card,i)=>{const ce=cardEl(card,c,i);ce.style.top=`calc(${i} * var(--offset))`;ce.style.zIndex=i;el.appendChild(ce)});el.addEventListener('pointerup',()=>{if(drag)finishDrag(c)});t.appendChild(el)})}
  function beginDrag(ev,c,i){if(paused||state.finished||drag||ev.button!==0)return;if(!isRun(state.columns[c],i))return;ev.preventDefault();const run=state.columns[c].slice(i);drag={id:ev.pointerId,c,i,run,ghost:makeGhost(run),startX:ev.clientX,startY:ev.clientY};document.body.setPointerCapture?.(ev.pointerId);document.addEventListener('pointermove',onDrag);document.addEventListener('pointerup',onPointerUp,{once:true});document.addEventListener('pointercancel',cancelDrag,{once:true});positionGhost(ev.clientX,ev.clientY);document.querySelectorAll(`.card[data-col="${c}"]`).forEach(x=>{if(+x.dataset.index>=i)x.style.opacity='.15'})}
  function makeGhost(run){const g=document.createElement('div');g.className='drag-ghost';g.style.width='var(--cardW)';g.style.height=`calc(var(--cardH) + ${Math.max(0,run.length-1)} * var(--offset))`;run.forEach((card,i)=>{const e=cardEl(card,0,i);e.style.top=`calc(${i} * var(--offset))`;e.style.left='0';e.style.width='var(--cardW)';e.style.pointerEvents='none';g.appendChild(e)});$('dragLayer').appendChild(g);return g}
  function positionGhost(x,y){if(!drag)return;drag.ghost.style.transform=`translate3d(${x-drag.ghost.offsetWidth/2}px,${y-20}px,0)`}
  function onDrag(ev){if(!drag||ev.pointerId!==drag.id)return;positionGhost(ev.clientX,ev.clientY)}
  function onPointerUp(ev){if(!drag||ev.pointerId!==drag.id)return;const el=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.column');finishDrag(el?+el.dataset.col:-1)}
  function finishDrag(to){if(!drag)return;const d=drag;cleanupDrag();if(to>=0)move(d.c,d.i,to);else render()}
  function cancelDrag(){if(!drag)return;cleanupDrag();render()}
  function cleanupDrag(){if(!drag)return;drag.ghost?.remove();document.querySelectorAll('.card').forEach(x=>x.style.opacity='');document.removeEventListener('pointermove',onDrag);drag=null}
  function checkEnd(){if(state.completed>=SEQS)return end(true);if(!state.stock.length&&legalMoves().length===0)return end(false)}
  function showEndModal(){const win=state.completed>=SEQS;$('endIcon').textContent=win?'🏆':'🕸️';$('endTitle').textContent=win?'Победа!':'Игра окончена';$('endText').textContent=win?'Все 8 последовательностей собраны. Партия завершена — продолжение не предлагается.':'Больше нет доступных ходов и резерв пуст. Партия завершена.';$('endMoves').textContent=state.moves;$('endScore').textContent=state.score;$('endTime').textContent=fmt(elapsed());$('endModal').classList.remove('hidden')}
  function end(win){if(state.finished)return;state.finished=true;state.elapsedBase=elapsed();state.startedAt=0;stopTimer();recordStat(win?'win':'loss');save();render();showEndModal()}
  function toast(msg){const t=$('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2600)}
  function getStats(){try{return Object.assign({started:0,finished:0,wins:0,losses:0,bestScore:0,bestTime:null},JSON.parse(localStorage.getItem(STATS_KEY)||'{}'))}catch(e){return {started:0,finished:0,wins:0,losses:0,bestScore:0,bestTime:null}}}
  function recordStat(type){const s=getStats();if(type==='started')s.started++;if(type==='win'){s.finished++;s.wins++;s.bestScore=Math.max(s.bestScore,state.score);const t=elapsed();s.bestTime=s.bestTime==null?t:Math.min(s.bestTime,t)}if(type==='loss')s.finished++;localStorage.setItem(STATS_KEY,JSON.stringify(s))}
  function save(){if(!state)return;localStorage.setItem(KEY,JSON.stringify({state,history,paused}))}
  function hasSavedGame(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');return !!(d&&d.state&&Array.isArray(d.state.columns)&&!d.state.finished)}catch(e){return false}}
  function updateContinue(){const b=$('continueMenuBtn');b.classList.toggle('hidden',!hasSavedGame())}
  function openInfo(kind){const data={
    rules:{icon:'📖',title:'Правила игры',html:'<h3>Цель</h3><p>Соберите <strong>8 полных последовательностей K–A</strong> одной масти.</p><h3>Перенос стопки</h3><p>Целиком можно переносить только открытую стопку, которая идёт строго по убыванию и состоит <strong>только из одной масти</strong>. Смешанная по мастям цепочка целиком не переносится — карты разбираются по одной.</p><h3>Обычный ход</h3><p>Открытую карту можно положить на карту ровно на один ранг старше. Масть при таком ходе не важна. В пустой столбец можно перенести любую допустимую одиночную карту или целую одно-мастную стопку.</p><h3>Раздача</h3><p>В резерве 50 карт: 5 раздач по одной карте в каждый из 10 столбцов. Если есть пустой столбец, новая раздача запрещена.</p>'},
    stats:{icon:'🏆',title:'Статистика',html:statsHtml()},
    about:{icon:'ℹ️',title:'О разработчиках',html:'<p><strong>SANI GROUP</strong></p><p>ПАУК — локальный классический пасьянс с режимами 1, 2 и 4 масти.</p><p>Интерфейс и игровая логика рассчитаны на компьютер и сенсорные устройства.</p>'}
  }[kind];$('infoIcon').textContent=data.icon;$('infoTitle').textContent=data.title;$('infoBody').innerHTML=data.html;$('infoModal').classList.remove('hidden')}
  function statsHtml(){const s=getStats();return `<h3>Ваши результаты</h3><p>Начато партий: <strong>${s.started}</strong></p><p>Завершено: <strong>${s.finished}</strong></p><p>Побед: <strong>${s.wins}</strong></p><p>Поражений: <strong>${s.losses}</strong></p><p>Лучший счёт: <strong>${s.bestScore}</strong></p><p>Лучшее время: <strong>${s.bestTime==null?'—':fmt(s.bestTime)}</strong></p>`}
  function openMenu(){if(state&&!state.finished&&!paused){state.elapsedBase=elapsed();state.startedAt=0;paused=true;save()}stopTimer();clearHint();$('pauseModal').classList.add('hidden');$('endModal').classList.add('hidden');$('gameScreen').classList.add('hidden');$('startScreen').classList.remove('hidden');updateContinue()}
  function continueGame(){if(!state||state.finished){if(!loadSavedIntoMemory())return}paused=false;state.startedAt=Date.now();$('startScreen').classList.add('hidden');$('gameScreen').classList.remove('hidden');$('pauseModal').classList.add('hidden');$('endModal').classList.add('hidden');render();startTimer();save()}
  function loadSavedIntoMemory(){try{const raw=localStorage.getItem(KEY);if(!raw)return false;const d=JSON.parse(raw);if(!d.state||!Array.isArray(d.state.columns)||d.state.finished)return false;state=d.state;history=Array.isArray(d.history)?d.history:[];state.startedAt=0;paused=true;return true}catch(e){return false}}
  function load(){if(!loadSavedIntoMemory())return false;$('gameScreen').classList.add('hidden');$('startScreen').classList.remove('hidden');updateContinue();return true}
  function toMenu(){openMenu()}
  document.querySelectorAll('.mode-choice').forEach(b=>b.addEventListener('click',()=>{$('modeModal').classList.add('hidden');newGame(+b.dataset.suits)}));$('newGameMenuBtn').addEventListener('click',()=>$('modeModal').classList.remove('hidden'));$('modesMenuBtn').addEventListener('click',()=>$('modeModal').classList.remove('hidden'));$('continueMenuBtn').addEventListener('click',continueGame);$('rulesMenuBtn').addEventListener('click',()=>openInfo('rules'));$('statsMenuBtn').addEventListener('click',()=>openInfo('stats'));$('aboutMenuBtn').addEventListener('click',()=>openInfo('about'));$('modeCloseBtn').addEventListener('click',()=>$('modeModal').classList.add('hidden'));$('infoCloseBtn').addEventListener('click',()=>$('infoModal').classList.add('hidden'));$('dealBtn').addEventListener('click',deal);$('undoBtn').addEventListener('click',undo);$('hintBtn').addEventListener('click',hint);$('pauseBtn').addEventListener('click',()=>pauseGame(false));$('resumeBtn').addEventListener('click',resumeGame);$('menuBtn').addEventListener('click',toMenu);$('pauseMenuBtn').addEventListener('click',toMenu);$('endMenuBtn').addEventListener('click',toMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape')cancelDrag();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z')undo()});document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGame(true)});window.addEventListener('blur',()=>pauseGame(true));window.addEventListener('pagehide',()=>{if(state&&!state.finished){if(!paused){state.elapsedBase=elapsed();state.startedAt=0}save()}});
  window.SANI_DEBUG={newGame,deal,undo,hint,getState:()=>clone(state),legalMoves};
  if(!load())$('startScreen').classList.remove('hidden');updateContinue();
})();
