const fs=require('fs'),vm=require('vm');
for(const f of ['index.html','style.css','client.js','server.js','package.json','logo-sani-group.svg','card-back.svg','felt-texture.svg','wood-texture.svg','favicon.svg'])if(!fs.existsSync(f))throw Error('Missing '+f);
const js=fs.readFileSync('client.js','utf8');new vm.Script(js);const html=fs.readFileSync('index.html','utf8');
for(const id of ['startScreen','gameScreen','tableau','dealBtn','hintBtn','undoBtn','pauseModal','endModal','newGameMenuBtn','continueMenuBtn','rulesMenuBtn','statsMenuBtn','aboutMenuBtn','modeModal','infoModal'])if(!html.includes('id="'+id+'"'))throw Error('Missing '+id);
if(!js.includes("const COLS=10,TOTAL=104,SEQS=8"))throw Error('Core constants missing');
if(!js.includes("const per=8/n"))throw Error('Deck distribution rule missing');
if(!js.includes('for(let c=0;c<10;c++){const count=c<4?6:5'))throw Error('54-card tableau layout missing');
if(!js.includes('while(d.length)stock.push(d.splice(0,10))'))throw Error('50-card reserve / 10-card deals missing');
if(!js.includes("col[k].suit!==col[k-1].suit||col[k].rank!==col[k-1].rank-1"))throw Error('Same-suit strict descending stack rule missing');
if(!js.includes("target[target.length-1].rank===card.rank+1"))throw Error('Placement rank rule missing');
if(!js.includes("if(state.columns.some(c=>c.length===0)"))throw Error('Empty-column reserve guard missing');
if(!js.includes("if(state.completed>=SEQS)return end(true)"))throw Error('Win condition missing');
if(!js.includes("if(!state.stock.length&&legalMoves().length===0)return end(false)"))throw Error('Loss condition missing');
if(!js.includes('state.finished=true'))throw Error('Finished state missing');
if(!js.includes('!d.state.finished'))throw Error('Finished games must not be offered as Continue');
if(!js.includes('if(moveBusy||paused||state.finished||!history.length||!state)return false'))throw Error('Undo must be blocked after final state');
if(!js.includes("state.score=Math.max(0,state.score-1);save();toast('Ход отменён • −1 очко')"))throw Error('Undo score penalty missing');
if(!js.includes("window.addEventListener('blur',()=>pauseGame(true))"))throw Error('Blur auto-pause missing');
if(!fs.readFileSync('server.js','utf8').includes("if(p==='/favicon.ico')p='/favicon.svg';"))throw Error('favicon.ico alias missing');
console.log('QA static: PASS');
console.log('Deck: 104 cards for 1/2/4 suits');
console.log('Layout: 54 tableau + 50 reserve, 5 deals of 10');
console.log('Stack rule: full tail only if strictly descending + same suit');
console.log('Reserve: blocked while any tableau column is empty');
console.log('Hint: 3 identical repeats -> deal suggestion');
console.log('End game: terminal win/loss state + no continuation');
console.log('Menu: new game / continue / modes / rules / statistics / about');
console.log('Undo: unlimited history + −1 score penalty');
console.log('Pause: visibility + blur + saved state');
console.log('Favicon: /favicon.ico served from favicon.svg');
